/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/vmzavUCSHOx
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function Pricingv2() {
  return (
    <section className="bg-gray-100 py-12 md:py-20 dark:bg-gray-950">
      <div className="container mx-auto px-4 md:px-6">
        <div className="mx-auto max-w-4xl text-center">
          <h2 className="text-3xl font-bold tracking-tight md:text-4xl">Pricing for Eventure</h2>
          <p className="mt-4 text-gray-500 dark:text-gray-400 md:text-xl">
            Choose the plan that fits your event management needs.
          </p>
        </div>
        <div className="mt-10 grid grid-cols-1 gap-6 md:grid-cols-3 md:gap-8 lg:gap-12">
          <div className="rounded-lg bg-white p-6 shadow-lg dark:bg-gray-800">
            <div className="mb-6 flex items-center justify-between">
              <h3 className="text-2xl font-bold">Basic</h3>
              <div className="text-4xl font-bold">
                $19
                <span className="text-gray-500 dark:text-gray-400 text-base">/mo</span>
              </div>
            </div>
            <ul className="space-y-4 text-gray-500 dark:text-gray-400">
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                Event Creation & Management
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                Guest List Management
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                Basic Email Notifications
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                Calendar Integration
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                Standard Support
              </li>
            </ul>
            <Button className="mt-6 w-full">Get Started</Button>
          </div>
          <div className="rounded-lg bg-white p-6 shadow-lg dark:bg-gray-800">
            <div className="mb-6 flex items-center justify-between">
              <h3 className="text-2xl font-bold">Pro</h3>
              <div className="text-4xl font-bold">
                $49
                <span className="text-gray-500 dark:text-gray-400 text-base">/mo</span>
              </div>
            </div>
            <ul className="space-y-4 text-gray-500 dark:text-gray-400">
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                All Basic plan features
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                Advanced Email Notifications & Reminders
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                Detailed Analytics & Reports
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                Priority Support
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                AI Integration for Event Recommendations
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                Social Media Integration & Promotion Tools
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                Advanced Security Features
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                24/7 Support
              </li>
            </ul>
            <Button className="mt-6 w-full">Get Started</Button>
          </div>
          <div className="rounded-lg bg-white p-6 shadow-lg dark:bg-gray-800">
            <div className="mb-6 flex items-center justify-between">
              <h3 className="text-2xl font-bold">Premium</h3>
              <div className="text-4xl font-bold">
                $99
                <span className="text-gray-500 dark:text-gray-400 text-base">/mo</span>
              </div>
            </div>
            <ul className="space-y-4 text-gray-500 dark:text-gray-400">
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                All Pro plan features
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                Dedicated Account Manager
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                Custom Branding & White-Labeling
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                Advanced Integrations & API Access
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                Unlimited Event Capacity
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                Personalized Onboarding & Training
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="h-5 w-5 text-green-500" />
                Guaranteed 99.99% Uptime SLA
              </li>
            </ul>
            <Button className="mt-6 w-full">Get Started</Button>
          </div>
        </div>
      </div>
    </section>
  )
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}
